/*
 * lgbm_shim.c
 *
 * Thin C translation unit that compiles lightgbm_model.h as C99.
 *
 * WHY THIS EXISTS
 * ---------------
 * lightgbm_model.h (generated by m2cgen / LightGBM C export) uses
 * compound literal syntax:
 *
 *     softmax((double[]){ var1 + var2 + ... }, 6, var0);
 *
 * In C99, compound literals are named temporaries with storage duration
 * and a well-defined address — this is valid.
 * In C++, the same syntax is a GCC extension treated as an rvalue
 * temporary, making its address ambiguous. GCC rejects it with:
 *   "error: taking address of temporary array"
 *
 * By placing the #include here in a .c file, PlatformIO invokes GCC in
 * C mode, where the compound literal is legal. sensor.cpp (C++) then
 * calls the functions via the extern "C" forward declarations below.
 *
 * IMPORTANT
 * ---------
 * Do not include lightgbm_model.h in any .cpp file directly. Use only
 * the extern "C" declarations in sensor.cpp.
 */

#include <math.h>    /* exp() used by softmax() inside lightgbm_model.h */
#include <string.h>  /* memcpy() — also included by the model header itself */
#include "lightgbm_model.h"
