#pragma once
// AUTO-GENERATED by split_rf_model.py — DO NOT EDIT MANUALLY
//
// Public interface for the split Random Forest model.
// sensor.cpp should #include this file instead of model_rf.h.

#include <stdint.h>

// ── Forward declarations for each compiled tree shard ──────────────────────
void rf_predict_part_0(const float *x, uint8_t votes[4]);
void rf_predict_part_1(const float *x, uint8_t votes[4]);
void rf_predict_part_2(const float *x, uint8_t votes[4]);
void rf_predict_part_3(const float *x, uint8_t votes[4]);
void rf_predict_part_4(const float *x, uint8_t votes[4]);
void rf_predict_part_5(const float *x, uint8_t votes[4]);
void rf_predict_part_6(const float *x, uint8_t votes[4]);
void rf_predict_part_7(const float *x, uint8_t votes[4]);
void rf_predict_part_8(const float *x, uint8_t votes[4]);
void rf_predict_part_9(const float *x, uint8_t votes[4]);
void rf_predict_part_10(const float *x, uint8_t votes[4]);
void rf_predict_part_11(const float *x, uint8_t votes[4]);
void rf_predict_part_12(const float *x, uint8_t votes[4]);
void rf_predict_part_13(const float *x, uint8_t votes[4]);
void rf_predict_part_14(const float *x, uint8_t votes[4]);

// ── Inference wrapper ──────────────────────────────────────────────────────
namespace Eloquent {
    namespace ML {
        namespace Port {
            class RandomForest {
            public:
                /**
                 * Predict class index (0–3) for a feature vector.
                 * Calls all rf_predict_part_N() functions in sequence and
                 * returns the class with the highest vote count (argmax).
                 */
                int predict(const float *x) const {
                    uint8_t votes[4] = { 0 };

                    // Call each translation unit's sub-predict
                    rf_predict_part_0(x, votes);
    rf_predict_part_1(x, votes);
    rf_predict_part_2(x, votes);
    rf_predict_part_3(x, votes);
    rf_predict_part_4(x, votes);
    rf_predict_part_5(x, votes);
    rf_predict_part_6(x, votes);
    rf_predict_part_7(x, votes);
    rf_predict_part_8(x, votes);
    rf_predict_part_9(x, votes);
    rf_predict_part_10(x, votes);
    rf_predict_part_11(x, votes);
    rf_predict_part_12(x, votes);
    rf_predict_part_13(x, votes);
    rf_predict_part_14(x, votes);

                    // Argmax: return the class with the most votes
                    uint8_t classIdx = 0;
                    float maxVotes = votes[0];
                    for (uint8_t i = 1; i < 4; i++) {
                        if (votes[i] > maxVotes) {
                            classIdx = i;
                            maxVotes = votes[i];
                        }
                    }
                    return classIdx;
                }

                /** Predict and return human-readable label. */
                const char* predictLabel(const float *x) const {
                    return idxToLabel(predict(x));
                }

                /** Map class index to label string. */
                const char* idxToLabel(uint8_t classIdx) const {
                    switch (classIdx) {
                        case 0: return "0";
                        case 1: return "1";
                        case 2: return "2";
                        case 3: return "3";
                        default: return "unknown";
                    }
                }
            };
        }
    }
}
