#!/usr/bin/env python3
"""
split_rf_model.py
-----------------
Splits the monolithic Eloquent Random Forest header (model_rf.h) into
multiple .cpp translation units (TUs) so that each one compiles a
small enough portion of the predict() body to fit within the Xtensa
LX6 l32r address range (~256 KB per TU).

Strategy:
  - Parse out each tree block (between "// tree #N" markers).
  - Group TREES_PER_FILE trees into a single TU.
  - Each TU defines a free function:
        void rf_predict_part_N(const float *x, uint8_t votes[4]);
    that runs its trees and accumulates votes[] in-place.
  - A thin wrapper header (model_rf_split.h) declares all part functions
    and provides the final predict() / predictLabel() / idxToLabel() logic.

Output files (written into hardware/sensor/src/):
  rf_part_0.cpp, rf_part_1.cpp, ... rf_part_N.cpp
  (plus model_rf_split.h into hardware/sensor/include/)
"""

import re
import os

# ── Configuration ──────────────────────────────────────────────────────────────
MODEL_H         = "/home/hackastic/Proglang/IOT/Encok-Cok/model/model_rf.h"
# model/ is gitignored; regenerate any time the ML model is retrained
OUT_SRC_DIR     = "/home/hackastic/Proglang/IOT/Encok-Cok/hardware/sensor/model"
OUT_INCLUDE_DIR = "/home/hackastic/Proglang/IOT/Encok-Cok/hardware/sensor/include"
TREES_PER_FILE  = 50      # 50 trees/TU keeps each function well under 256KB
NUM_CLASSES     = 4
# ──────────────────────────────────────────────────────────────────────────────

def read_model(path):
    with open(path, "r") as f:
        return f.read()

def extract_trees(source):
    """
    Returns a list of strings, one per tree body.
    Each string is the raw code between one '// tree #N' marker
    and the next (exclusive), stripped of leading/trailing whitespace.
    Also returns the argmax return block (after all trees).
    """
    # Split on '// tree #N' — keep delimiter
    parts = re.split(r'(\s+// tree #\d+\n)', source)

    trees = []
    current = ""
    for part in parts:
        if re.match(r'\s+// tree #\d+\n', part):
            if current.strip():
                trees.append(current.strip())
            current = part
        else:
            current += part

    # The last chunk contains the argmax block — split it off
    if current.strip():
        trees.append(current.strip())

    return trees

def extract_predict_body(source):
    """
    Extracts everything inside the predict(float *x) { ... } method body.
    Returns the list of per-tree code blocks and the final argmax block.
    """
    # Find the opening brace of predict()
    m = re.search(r'int predict\(float \*x\) \{', source)
    if not m:
        raise ValueError("predict() not found in model header")
    start = m.end()

    # Walk the string counting braces to find the matching closing brace
    depth = 1
    i = start
    while i < len(source) and depth > 0:
        if source[i] == '{':
            depth += 1
        elif source[i] == '}':
            depth -= 1
        i += 1
    body = source[start:i-1]  # everything inside predict() { ... }

    # Strip the argmax/return tail block at the end of the body.
    # The tail starts at "// return argmax of votes" and goes to the end.
    tail_match = re.search(r'\s+// return argmax of votes.*$', body, re.DOTALL)
    if tail_match:
        tail_block = tail_match.group(0).strip()
        body = body[:tail_match.start()]
    else:
        tail_block = ""

    # Split the remaining body into individual tree blocks
    blocks = re.split(r'(?=\s+// tree #\d+\n)', body)

    tree_blocks = []
    for block in blocks:
        stripped = block.strip()
        if not stripped:
            continue
        if re.match(r'// tree #\d+', stripped):
            tree_blocks.append(stripped)

    return tree_blocks, tail_block

def write_part_cpp(part_idx, trees, out_dir):
    """Write one rf_part_N.cpp containing TREES_PER_FILE trees."""
    lines = []
    lines.append("// AUTO-GENERATED by split_rf_model.py — DO NOT EDIT MANUALLY")
    lines.append("// This file contains a subset of the Random Forest trees.")
    lines.append("// Each tree accumulates votes into the shared votes[] array.")
    lines.append("")
    lines.append('#include "model_rf_split.h"')
    lines.append("")
    lines.append(f"void rf_predict_part_{part_idx}(const float *x, uint8_t votes[{NUM_CLASSES}]) {{")
    for tree in trees:
        lines.append("    " + tree.replace("\n", "\n    "))
        lines.append("")
    lines.append("}")
    lines.append("")

    path = os.path.join(out_dir, f"rf_part_{part_idx}.cpp")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {path}  ({len(trees)} trees)")

def write_header(num_parts, tail_block, out_include_dir):
    """Write model_rf_split.h — the public interface used by sensor.cpp."""
    forward_decls = "\n".join(
        f"void rf_predict_part_{i}(const float *x, uint8_t votes[{NUM_CLASSES}]);"
        for i in range(num_parts)
    )
    calls = "\n    ".join(
        f"rf_predict_part_{i}(x, votes);"
        for i in range(num_parts)
    )

    header = f"""\
#pragma once
// AUTO-GENERATED by split_rf_model.py — DO NOT EDIT MANUALLY
//
// Public interface for the split Random Forest model.
// sensor.cpp should #include this file instead of model_rf.h.

#include <stdint.h>

// ── Forward declarations for each compiled tree shard ──────────────────────
{forward_decls}

// ── Inference wrapper ──────────────────────────────────────────────────────
namespace Eloquent {{
    namespace ML {{
        namespace Port {{
            class RandomForest {{
            public:
                /**
                 * Predict class index (0–{NUM_CLASSES-1}) for a feature vector.
                 * Calls all rf_predict_part_N() functions in sequence and
                 * returns the class with the highest vote count (argmax).
                 */
                int predict(const float *x) const {{
                    uint8_t votes[{NUM_CLASSES}] = {{ 0 }};

                    // Call each translation unit's sub-predict
                    {calls}

                    // Argmax: return the class with the most votes
                    uint8_t classIdx = 0;
                    float maxVotes = votes[0];
                    for (uint8_t i = 1; i < {NUM_CLASSES}; i++) {{
                        if (votes[i] > maxVotes) {{
                            classIdx = i;
                            maxVotes = votes[i];
                        }}
                    }}
                    return classIdx;
                }}

                /** Predict and return human-readable label. */
                const char* predictLabel(const float *x) const {{
                    return idxToLabel(predict(x));
                }}

                /** Map class index to label string. */
                const char* idxToLabel(uint8_t classIdx) const {{
                    switch (classIdx) {{
                        case 0: return "0";
                        case 1: return "1";
                        case 2: return "2";
                        case 3: return "3";
                        default: return "unknown";
                    }}
                }}
            }};
        }}
    }}
}}
"""
    path = os.path.join(out_include_dir, "model_rf_split.h")
    with open(path, "w") as f:
        f.write(header)
    print(f"  Wrote {path}")

def main():
    print("Reading model...")
    source = read_model(MODEL_H)

    print("Extracting trees...")
    tree_blocks, tail_block = extract_predict_body(source)
    total_trees = len(tree_blocks)
    print(f"  Found {total_trees} trees")

    os.makedirs(OUT_SRC_DIR, exist_ok=True)
    os.makedirs(OUT_INCLUDE_DIR, exist_ok=True)

    # Remove any previously generated rf_part_*.cpp files
    for f in os.listdir(OUT_SRC_DIR):
        if f.startswith("rf_part_") and f.endswith(".cpp"):
            os.remove(os.path.join(OUT_SRC_DIR, f))
            print(f"  Removed old {f}")

    print(f"Writing part files ({TREES_PER_FILE} trees/file)...")
    num_parts = 0
    for i in range(0, total_trees, TREES_PER_FILE):
        chunk = tree_blocks[i:i + TREES_PER_FILE]
        write_part_cpp(num_parts, chunk, OUT_SRC_DIR)
        num_parts += 1

    print(f"Writing header (model_rf_split.h) with {num_parts} parts...")
    write_header(num_parts, tail_block, OUT_INCLUDE_DIR)

    print(f"\nDone. {total_trees} trees split into {num_parts} TUs.")
    print("Next: update sensor.cpp to #include \"model_rf_split.h\" instead of \"model_rf.h\"")

if __name__ == "__main__":
    main()
